### ISSUE TITLE
云函数打卡失败

### ISSUE THREAD

**Issue by wfmbuyaofangqi** [yin1999/healthreport_fc#23]
研究生打卡系统添加了一个体温选项，每次进入都得勾选，我想是不是这个问题导致自动打卡失败。目前阿里云配置的云函数版本用不了了，希望您能更新一下✨✨✨
![QQ截图20220502114040](https://user-images.githubusercontent.com/85282126/166181535-2e8b5555-7512-448d-ae0c-1f57e34ab04d.png)

**Comment by yin1999** [comment]
研究生使用的打卡系统目前和本科生的不一致（当前最新版本适配了奥蓝系统，未对老系统作适配），如果需要的话，请邮箱联系：yin199909@aliyun.com（提供一下账号密码，我另行适配）

**Comment by yin1999** [comment]
问题来自服务器返回的历史填报内容中，多了一个字段，而这一字段无需 POST 到服务器：

```js
{
	"USERID": "XXX",
	"CLRQ": "XXX",
	"XGH_566872": "XXX",
	"XM_140773": "XXX",
	"SFZJH_402404": "XXX",
	"SZDW_439708": "XXX",
	"ZY_878153": "XXX",
	"GDXW_926421": "XXX",
	"DSNAME_606453": "XXX",
	"PYLB_253720": "XXX",
	"SELECT_172548": "XXX",
	"TEXT_91454": "XXX",
	"TEXT_24613": "XXX",
	"TEXT_826040": "XXX",
	"RADIO_799044": "XXX",
	"RADIO_384811": "XXX",
	"RADIO_907280": "XXX",
	"RADIO_716001": "XXX",
	"RADIO_248990": "XXX",
	"RN": 1 // 这个字段是新增，但无需 POST 到服务器的
}
```

**Comment by yin1999** [comment]
你试试这个版本是否可用：https://github.com/yin1999/healthreport_fc/releases/tag/v0.2.3
